name: discord-notifier
# when to run the workflow
on:
  release:
    types: [published]
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    if: github.actor == 'sindre0830'
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v3

    - name: send message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        username: "GitHub Bot"
        message: "Update $GITHUB_REF_NAME is out! Check out the changelog here https://github.com/RimNauts/RimNauts2/releases/$GITHUB_REF_NAME"
