name: tmp
# when to run the workflow
on:
  workflow_dispatch:
# instructions the workflow will perform
jobs:
  build:
    if: github.actor == 'sindre0830'
    # environment to run on
    runs-on: ubuntu-latest
    # steps to perform
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        ref: ${{ github.sha }}

    - name: Send message to Discord server
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: "sindre0830"
        DISCORD_AVATAR: "https://i.imgur.com/cEgyvGu.jpg"
        DISCORD_EMBEDS: ${{ toJson(./Changelog.md) }}
        NEW_TAG: "v3.2.1"
      with:
        args: "<@&1067088830999560212> New update is out! Check out the changelog here <https://github.com/RimNauts/RimNauts2/releases/tag/{{ NEW_TAG }}>"
